{% set name = "ipynbname" %}
{% set version = "2023.2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 462bbdd7956624876dc4ea81fa792845ab3870e444ca1f6b7acdaea37d8c9ebf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - ipykernel

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipynbname

about:
  home: https://github.com/msm1089/ipynbname
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple utility that retrieves current Jupyter notebook filename or path, when run from Jupyter notebook
  dev_url: https://github.com/msm1089/ipynbname

extra:
  recipe-maintainers:
    - DamienIrving
    - msm1089
